/* Generated by re2c 1.0.1 on Mon Jun  8 23:48:31 2020 */
#line 1 "lexer.xch"
// {{{ GPL License

// This file is part of gringo - a grounder for logic programs.
// Copyright (C) 2013  Roland Kaminski

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// }}}



#include <gringo/locatable.hh>
#include "plogparser.h"

#define YYCTYPE     char
#define YYCURSOR    cursor()
#define YYLIMIT     limit()
#define YYMARKER    marker()
#define YYFILL(n)   {fill(n);}
#define YYCTXMARKER ctxmarker()
#define YYGETCONDITION condition
#define YYSETCONDITION condition



// settings: continue executing the loop when the condiiton is switched, e.g,
// in       <normal,theory,definition> "%"        :=> comment

#line 42 "lexer.xch"

//
// definitions:
#line 59 "lexer.xch"


using Location = Gringo::Location;

int PlogParser::lex_impl(void *pValue, Location &loc) {
    int bc = 0;
    auto &value = *static_cast<PlogGrammar::parser::semantic_type*>(pValue);
    start(loc);
    for (;;) {
        
#line 58 "<stdout>"
{
	YYCTYPE yych;
	switch (YYGETCONDITION()) {
	case yycnormal: goto yyc_normal;
	case yycblockcomment: goto yyc_blockcomment;
	case yyccomment: goto yyc_comment;
	}
/* *********************************** */
yyc_normal:
	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy5;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '#':	goto yy11;
	case '%':	goto yy12;
	case '&':	goto yy14;
	case '(':	goto yy16;
	case ')':	goto yy18;
	case '*':	goto yy20;
	case '+':	goto yy22;
	case ',':	goto yy24;
	case '-':	goto yy26;
	case '.':	goto yy28;
	case '/':	goto yy30;
	case '0':	goto yy32;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy34;
	case ':':	goto yy36;
	case '<':	goto yy38;
	case '=':	goto yy40;
	case '>':	goto yy42;
	case '?':	goto yy44;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy46;
	case '[':	goto yy49;
	case '\\':	goto yy51;
	case ']':	goto yy53;
	case 'a':	goto yy55;
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy57;
	case 'n':	goto yy59;
	case 'p':	goto yy60;
	case 's':	goto yy61;
	case '{':	goto yy62;
	case '|':	goto yy64;
	case '}':	goto yy66;
	default:	goto yy3;
	}
yy3:
	++YYCURSOR;
yy4:
#line 114 "lexer.xch"
	{ lexerError( std::string(string().first, string().first + string().size)); continue; }
#line 167 "<stdout>"
yy5:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy5;
	default:	goto yy7;
	}
yy7:
#line 69 "lexer.xch"
	{ start(loc); continue; }
#line 181 "<stdout>"
yy8:
	++YYCURSOR;
#line 71 "lexer.xch"
	{ if(eof()) return 0; step(); start(loc); continue; }
#line 186 "<stdout>"
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy68;
	default:	goto yy4;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case '!':	goto yy70;
	case 'a':
	case 'b':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy72;
	case 'c':	goto yy75;
	default:	goto yy4;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case '*':	goto yy76;
	default:	goto yy13;
	}
yy13:
	YYSETCONDITION(yyccomment);
	continue;
yy14:
	++YYCURSOR;
#line 98 "lexer.xch"
	{ return PlogGrammar::parser::token::AND; }
#line 238 "<stdout>"
yy16:
	++YYCURSOR;
#line 91 "lexer.xch"
	{ return PlogGrammar::parser::token::LPAREN; }
#line 243 "<stdout>"
yy18:
	++YYCURSOR;
#line 92 "lexer.xch"
	{ return PlogGrammar::parser::token::RPAREN; }
#line 248 "<stdout>"
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case '*':	goto yy78;
	default:	goto yy21;
	}
yy21:
#line 100 "lexer.xch"
	{ return PlogGrammar::parser::token::MUL; }
#line 258 "<stdout>"
yy22:
	++YYCURSOR;
#line 95 "lexer.xch"
	{ return PlogGrammar::parser::token::ADD; }
#line 263 "<stdout>"
yy24:
	++YYCURSOR;
#line 87 "lexer.xch"
	{ return PlogGrammar::parser::token::COMMA; }
#line 268 "<stdout>"
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy80;
	default:	goto yy27;
	}
yy27:
#line 96 "lexer.xch"
	{ return PlogGrammar::parser::token::SUB; }
#line 278 "<stdout>"
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy82;
	default:	goto yy29;
	}
yy29:
#line 83 "lexer.xch"
	{ return PlogGrammar::parser::token::DOT; }
#line 288 "<stdout>"
yy30:
	++YYCURSOR;
#line 109 "lexer.xch"
	{ return PlogGrammar::parser::token::SLASH; }
#line 293 "<stdout>"
yy32:
	++YYCURSOR;
yy33:
#line 79 "lexer.xch"
	{ value.num = integer(); return PlogGrammar::parser::token::NUMBER; }
#line 299 "<stdout>"
yy34:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy34;
	default:	goto yy33;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':	goto yy84;
	case '-':	goto yy86;
	default:	goto yy37;
	}
yy37:
#line 84 "lexer.xch"
	{ return PlogGrammar::parser::token::COLON; }
#line 327 "<stdout>"
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy88;
	case '>':	goto yy90;
	default:	goto yy39;
	}
yy39:
#line 102 "lexer.xch"
	{ return PlogGrammar::parser::token::LT; }
#line 338 "<stdout>"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy92;
	default:	goto yy41;
	}
yy41:
#line 108 "lexer.xch"
	{ return PlogGrammar::parser::token::EQ; }
#line 348 "<stdout>"
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy94;
	default:	goto yy43;
	}
yy43:
#line 101 "lexer.xch"
	{ return PlogGrammar::parser::token::GT; }
#line 358 "<stdout>"
yy44:
	++YYCURSOR;
#line 110 "lexer.xch"
	{ return PlogGrammar::parser::token::QUESTION; }
#line 363 "<stdout>"
yy46:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy48;
	}
yy48:
#line 80 "lexer.xch"
	{ value.str = String::toRep(string()); return PlogGrammar::parser::token::VARIABLE; }
#line 438 "<stdout>"
yy49:
	++YYCURSOR;
#line 89 "lexer.xch"
	{ return PlogGrammar::parser::token::LBRACK; }
#line 443 "<stdout>"
yy51:
	++YYCURSOR;
#line 99 "lexer.xch"
	{ return PlogGrammar::parser::token::MOD; }
#line 448 "<stdout>"
yy53:
	++YYCURSOR;
#line 90 "lexer.xch"
	{ return PlogGrammar::parser::token::RBRACK; }
#line 453 "<stdout>"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy96;
	default:	goto yy58;
	}
yy56:
#line 78 "lexer.xch"
	{ value.str = String::toRep(string()); return PlogGrammar::parser::token::IDENTIFIER; }
#line 463 "<stdout>"
yy57:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy58:
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy57;
	default:	goto yy56;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy97;
	default:	goto yy58;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy98;
	default:	goto yy58;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy100;
	case 't':	goto yy101;
	default:	goto yy58;
	}
yy62:
	++YYCURSOR;
#line 93 "lexer.xch"
	{ return PlogGrammar::parser::token::LBRACE; }
#line 559 "<stdout>"
yy64:
	++YYCURSOR;
#line 88 "lexer.xch"
	{ return PlogGrammar::parser::token::VBAR; }
#line 564 "<stdout>"
yy66:
	++YYCURSOR;
#line 94 "lexer.xch"
	{ return PlogGrammar::parser::token::RBRACE; }
#line 569 "<stdout>"
yy68:
	++YYCURSOR;
#line 106 "lexer.xch"
	{ return PlogGrammar::parser::token::NEQ; }
#line 574 "<stdout>"
yy70:
	++YYCURSOR;
	YYSETCONDITION(yyccomment);
	continue;
yy72:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy73:
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy72;
	default:	goto yy74;
	}
yy74:
#line 73 "lexer.xch"
	{ value.str = String::toRep(string(1)); return PlogGrammar::parser::token::SORT_NAME; }
#line 654 "<stdout>"
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy102;
	default:	goto yy73;
	}
yy76:
	++YYCURSOR;
	YYSETCONDITION(yycblockcomment);
#line 111 "lexer.xch"
	{ bc++; continue; }
#line 666 "<stdout>"
yy78:
	++YYCURSOR;
#line 97 "lexer.xch"
	{ return PlogGrammar::parser::token::POW; }
#line 671 "<stdout>"
yy80:
	++YYCURSOR;
#line 82 "lexer.xch"
	{ return PlogGrammar::parser::token::ARROW; }
#line 676 "<stdout>"
yy82:
	++YYCURSOR;
#line 81 "lexer.xch"
	{ return PlogGrammar::parser::token::DOTS; }
#line 681 "<stdout>"
yy84:
	++YYCURSOR;
#line 86 "lexer.xch"
	{ return PlogGrammar::parser::token::CRIF; }
#line 686 "<stdout>"
yy86:
	++YYCURSOR;
#line 85 "lexer.xch"
	{ return PlogGrammar::parser::token::IF; }
#line 691 "<stdout>"
yy88:
	++YYCURSOR;
#line 104 "lexer.xch"
	{ return PlogGrammar::parser::token::LEQ; }
#line 696 "<stdout>"
yy90:
	++YYCURSOR;
#line 107 "lexer.xch"
	{ return PlogGrammar::parser::token::NEQ; }
#line 701 "<stdout>"
yy92:
	++YYCURSOR;
#line 105 "lexer.xch"
	{ return PlogGrammar::parser::token::EQ; }
#line 706 "<stdout>"
yy94:
	++YYCURSOR;
#line 103 "lexer.xch"
	{ return PlogGrammar::parser::token::GEQ; }
#line 711 "<stdout>"
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy103;
	default:	goto yy58;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy104;
	default:	goto yy58;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy57;
	default:	goto yy99;
	}
yy99:
#line 70 "lexer.xch"
	{ return PlogGrammar::parser::token::PR; }
#line 796 "<stdout>"
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy106;
	default:	goto yy58;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy107;
	default:	goto yy58;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy108;
	default:	goto yy73;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy109;
	default:	goto yy58;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy57;
	default:	goto yy105;
	}
yy105:
#line 74 "lexer.xch"
	{ value.str = String::toRep(not_); return PlogGrammar::parser::token::NOT; }
#line 893 "<stdout>"
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy110;
	default:	goto yy58;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy111;
	default:	goto yy58;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy112;
	default:	goto yy73;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy113;
	default:	goto yy58;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy114;
	default:	goto yy58;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy116;
	default:	goto yy58;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy117;
	default:	goto yy73;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy119;
	default:	goto yy58;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy57;
	default:	goto yy115;
	}
yy115:
#line 75 "lexer.xch"
	{return PlogGrammar::parser::token::SORTDEFKEYWORD; }
#line 1014 "<stdout>"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy120;
	default:	goto yy58;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy72;
	default:	goto yy118;
	}
yy118:
#line 72 "lexer.xch"
	{ return PlogGrammar::parser::token::CONST; }
#line 1093 "<stdout>"
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy121;
	default:	goto yy58;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy122;
	default:	goto yy58;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy123;
	default:	goto yy58;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy124;
	default:	goto yy58;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy125;
	default:	goto yy58;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy126;
	default:	goto yy58;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy127;
	default:	goto yy58;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy129;
	default:	goto yy58;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy57;
	default:	goto yy128;
	}
yy128:
#line 76 "lexer.xch"
	{ return PlogGrammar::parser::token:: ATTDEFKEYWORD; }
#line 1214 "<stdout>"
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy57;
	default:	goto yy130;
	}
yy130:
#line 77 "lexer.xch"
	{ return PlogGrammar::parser::token:: STMTDEFKEYWORD; }
#line 1287 "<stdout>"
/* *********************************** */
yyc_blockcomment:
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy135;
	case '%':	goto yy137;
	case '*':	goto yy139;
	default:	goto yy133;
	}
yy133:
	++YYCURSOR;
yy134:
#line 120 "lexer.xch"
	{ continue; }
#line 1303 "<stdout>"
yy135:
	++YYCURSOR;
#line 119 "lexer.xch"
	{ if(eof()) { lexerError("<EOF>"); return 0; } step(); continue; }
#line 1308 "<stdout>"
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case '*':	goto yy140;
	default:	goto yy138;
	}
yy138:
	YYSETCONDITION(yyccomment);
	continue;
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case '%':	goto yy142;
	default:	goto yy134;
	}
yy140:
	++YYCURSOR;
#line 117 "lexer.xch"
	{ bc++; continue; }
#line 1328 "<stdout>"
yy142:
	++YYCURSOR;
#line 116 "lexer.xch"
	{ if(--bc == 0) { condition(yycnormal); start(loc); } continue; }
#line 1333 "<stdout>"
/* *********************************** */
yyc_comment:
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy148;
	default:	goto yy146;
	}
yy146:
	++YYCURSOR;
#line 135 "lexer.xch"
	{ continue; }
#line 1346 "<stdout>"
yy148:
	++YYCURSOR;
#line 122 "lexer.xch"
	{
            if(eof()) {
                if(bc > 0) { lexerError("<EOF>"); }
                return 0;
            }
            step();
            if (bc > 0) { condition(yycblockcomment); }
            else {
                condition(yycnormal);
                start(loc);
            }
            continue;
        }
#line 1363 "<stdout>"
}
#line 136 "lexer.xch"

    }
    assert(false);
    return 0;
}

#undef YYCTYPE
#undef YYCURSOR
#undef YYLIMIT
#undef YYMARKER
#undef YYFILL
#undef YYCTXMARKER
#undef YYGETCONDITION
#undef YYSETCONDITION
